### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by Yusuboy** [xelmas/Tiralabra-pakkausalgoritmit#1]
ladattu 20.4 klo 23:05. 
Terve!

Meillä näyttää olevan sama aihe😊

Huffman-koodausta ja LZW-algoritmia koskevat luokkasi ja metodisi näyttävät hyvältä rakenteeltaan ja järjestykseltään. Tässä muutamia ehdotuksia ja huomioita:

1. Hienoa työtä koodin dokumentoinnissa, missä selitetään sekä luokat että metodit. 👍
2. Koodisi muuttujien nimet ovat hyvin kuvaavia.
3. Koodiasi on helppo seurata ja ymmärtää, mikä tekee siitä erittäin käyttäjäystävällisen. 👌
4. Huomasin, että koodisi olettaa syöttötekstin olevan kelvollinen. Olisi ehkä hyvä lisätä virheidenkäsittelyä tapauksia varten, joissa syötteet ovat virheellisiä, esimerkiksi tyhjä teksti tiedostossa. Huomasin, että tällöin ohjelma kaatuu. Mutta kokonaisuudessaan algoritmien toteutus vaikuttaa kaiken kaikkiaan tehokkaalta. 👍
5. Olet tehnyt hienoa työtä testien kanssa! Testikattavuus näyttää todella hyvältä. Kaiken kaikkiaan testisi osoittavat, että Huffman-koodauksen ja LZW-toteutuksen oikeellisuutta on pyritty varmistamaan perusteellisesti. 👍
tykkäsin todella paljon UI:n toteutuksesta. 

Sinulla on selkeä ja hyvin dokumentoitu koodi, jota on helppo seurata ja ymmärtää. Voisit parantaa virheidenkäsittelyä varmistaaksesi ohjelman vakaan toiminnan kaikissa tilanteissa. Lisäksi testisi ovat kattavia ja osoittavat, että algoritmit on testattu perusteellisesti. Hyvää työtä!

**Comment by xelmas** [comment]
Hei! 
Kiitos palautteesta, hyviä huomioita. Lisäilin virheidenkäsittelyjä tähän seuraavaan versioon.
